### ISSUE TITLE
Intervalo de Data + Hora com jquery

### ISSUE THREAD

**Issue by eltongarbin** [Elton-Garbin/TCC-2016#21]
@GabrielFn realizar as seguintes alterações em /ScrumMaster/Sprint/Index
- [ ] Ajustar para permitir informar uma data no formato pt-BR
- [ ] Incluir plugin para apresentar e informar a data + hora. Exemplo: http://xdsoft.net/jqplugins/datetimepicker
- [ ] Realizar testes mais aprofundados na tela

**Comment by GabrielFn** [comment]
#24
