### ISSUE TITLE
Cadastro de Usuários

### ISSUE THREAD

**Issue by eltongarbin** [Elton-Garbin/TCC-2016#68]
@GabrielFn 

- [ ] Testar a implementação feita para tratar o envio de email caso não possuir internet, ou não tiver configurado;
- [ ] Validar Email já cadastrado;
- [ ] Validar UserName já cadastrado.

**Comment by eltongarbin** [comment]
Tenta melhorar a aparência da tela também.

**Comment by GabrielFn** [comment]
Adequado no commit #69
