### ISSUE TITLE
Documental

### ISSUE THREAD

**Issue by eltongarbin** [Elton-Garbin/TCC-2016#74]
@GabrielFn realize por favor o check-list abaixo para conclusão da issue:

- [x] Incorporar o diagrama de classe;
- [x] Atualizar os prints das telas do sistema;
- [x] Revisar a estrutura e verificar a ortografia;
- [x] Ler o documento;
- [x] Verificar o resumo e colocar sua conclusão.

**Comment by GabrielFn** [comment]
Feito
Incorporar o diagrama de classe
Atualizar os prints das telas do sistema

#76

**Comment by eltongarbin** [comment]
@GabrielFn 

Os diagramas de classes devem ser no padrão uml preto e branco, como foi definido pelo que conversei com o professor.
Verificar se não dá para ajeitar para colocar deitado o diagrama no item 3.1.3.3

**Comment by eltongarbin** [comment]
@GabrielFn  verificar se está correto a folha de aprovação (qualquer coisa vê com o pessoal da sala)
